src/objects/Bike__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                    <default>true</default>
                    <label>USD</label>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>SEK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Bike</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bikes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Free_Currency_Api_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Api_Key__c</fullName>
        <label>Api Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Free Currency Api Settings</label>
</CustomObject>

src/objects/Replacement_Part__c.object
<CustomObject>
    <fields>
        <fullName>Bike__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bike</label>
        <referenceTo>Bike__c</referenceTo>
        <relationshipLabel>Replacement Parts</relationshipLabel>
        <relationshipName>Replacement_Parts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>TEXT(Bike__r.Currency__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Replacement Part</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Replacement Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
public inherited sharing class TestDataFactory {

    public static Bike__c setupSingleTestBike(String bikeName, Decimal bikePrice, String bikeCurrency, Boolean isInsert) {
        Bike__c testBike = new Bike__c(Name = bikeName, Price__c = bikePrice, Currency__c = bikeCurrency);
        if (isInsert) {
            insert testBike;
        }
        return testBike;
    }

    public static Replacement_Part__c setupSingleTestReplacementPart(Id bikeId, String partName, Decimal partPrice, Boolean isInsert) {
        Replacement_Part__c testRP = new Replacement_Part__c(Name = partName, Price__c = partPrice, Bike__c = bikeId);
        if (isInsert) {
            insert testRP;
        }
        return testRP;
    }

    public static Free_Currency_Api_Settings__c setupSingleTestFreeCurrencyApiSetting(String apiKey, String name, Boolean isInsert) {
        Free_Currency_Api_Settings__c testSettings = new Free_Currency_Api_Settings__c(Name = name, Api_Key__c = apiKey);
        if (isInsert) {
            insert testSettings;
        }
        return testSettings;
    }
}