src/objects/Bike__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                    <default>true</default>
                    <label>USD</label>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>SEK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Bike</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bikes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c.object
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BikeChangeCurrencyController_Test.cls
@IsTest
public with sharing class BikeChangeCurrencyController_Test {

    @TestSetup
    static void createCommonTestData() {
        TestDataFactory.setupSingleTestFreeCurrencyApiSetting('testApiKey', ConstantsClass.FREE_PLAN_KEY_STRING, true);
    }

    @IsTest
    static void getCurrentRateAndUpdateRecordPositiveTest1() {
        Bike__c testBike = TestDataFactory.setupSingleTestBike('Foxx Caiman', 1000, 'USD', true);
        TestDataFactory.setupSingleTestReplacementPart(testBike.Id, 'Test Part Name', 100, true);

        // Set mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        BikeChangeCurrencyController.getCurrentRateAndUpdateRecord(testBike.Id, 'EUR');
        Test.stopTest();

        Bike__c updatedBike = [SELECT Id, Currency__c, Price__c FROM Bike__c WHERE Name = 'Foxx Caiman' LIMIT 1];

        System.assertEquals('EUR', updatedBike.Currency__c);
        System.assertEquals(925.17, updatedBike.Price__c.setScale(2));
    }

    @IsTest
    static void getCurrentRateAndUpdateRecordPositiveTest2() {
        Bike__c testBike = TestDataFactory.setupSingleTestBike('Foxx Caiman', 1000, 'EUR', true);
        TestDataFactory.setupSingleTestReplacementPart(testBike.Id, 'Test Part Name', 100, true);
        // Set mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        BikeChangeCurrencyController.getCurrentRateAndUpdateRecord(testBike.Id, 'USD');
        Test.stopTest();

        Bike__c updatedBike = [SELECT Id, Currency__c, Price__c FROM Bike__c WHERE Name = 'Foxx Caiman' LIMIT 1];

        System.assertEquals('USD', updatedBike.Currency__c);
        System.assertEquals(1080.88, updatedBike.Price__c.setScale(2));
    }

    @IsTest
    static void getCurrentRateAndUpdateRecordPositiveTest3() {
        Bike__c testBike = TestDataFactory.setupSingleTestBike('Foxx Caiman', 1000, 'EUR', true);
        TestDataFactory.setupSingleTestReplacementPart(testBike.Id, 'Test Part Name', 100, true);
        // Set mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        BikeChangeCurrencyController.getCurrentRateAndUpdateRecord(testBike.Id, 'SEK');
        Test.stopTest();

        Bike__c updatedBike = [SELECT Id, Currency__c, Price__c FROM Bike__c WHERE Name = 'Foxx Caiman' LIMIT 1];

        System.assertEquals('SEK', updatedBike.Currency__c);
        System.assertEquals(11382.72, updatedBike.Price__c.setScale(2));
    }

    @IsTest
    static void getCurrentRateAndUpdateRecordNegativeTest1() {
        Bike__c testBike = TestDataFactory.setupSingleTestBike('Foxx Caiman', 1000, 'EUR', true);
        // Set mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        BikeChangeCurrencyController.getCurrentRateAndUpdateRecord(testBike.Id, 'PLN');
        Test.stopTest();

        System.assertEquals(1, [SELECT Id FROM Error_Log__c].size());

    }

}